### ISSUE TITLE
soundworks-streaming not working for me

### ISSUE THREAD

**Issue by ryanh31** [collective-soundworks/soundworks-streaming#1]
Hi
I have been successful at running the drops and soundfield examples for soundworks. I am interested in streaming audio files to clients (large audio files, eventually different files to different clients). I am trying to run this example and it is giving me the following errors. I updadated node to the newest 11.4.0, in researching the issue, it will not give this error in node v 3.0.0, but this won't run in that early of a version.
I am running npm version 6.4.1
do you have any thoughts on how I can fix this?

computor:soundworks-streaming-master computoruser$ npm run start

> soundworks-audio-stream-manager-example@2.2.0 start /Users/computoruser/Documents/soundworks-streaming-master
> node ./bin/runner --start

[deprecated] AudioStreamManager unstable API is now deprecated - API will change in soundworks#v3.0.0, please consider updating your application
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.join (path.js:1155:7)
    at join (/Users/computoruser/Documents/soundworks-streaming-master/node_modules/soundworks/server/services/AudioStreamManager.js:152:29)
    at AudioStreamManager.processFile [as prepareStreamChunks] (/Users/computoruser/Documents/soundworks-streaming-master/node_modules/soundworks/server/services/AudioStreamManager.js:179:5)
    at AudioStreamManager.prepareStreamChunks (/Users/computoruser/Documents/soundworks-streaming-master/node_modules/soundworks/server/services/AudioStreamManager.js:95:12)
    at SignalAll.observer (/Users/computoruser/Documents/soundworks-streaming-master/node_modules/soundworks/utils/Signal.js:16:9)
    at /Users/computoruser/Documents/soundworks-streaming-master/node_modules/soundworks/utils/SignalAll.js:27:7
    at Signal.observer [as set] (/Users/computoruser/Documents/soundworks-streaming-master/node_modules/soundworks/utils/Signal.js:16:9)
    at Sync.set [as ready] (/Users/computoruser/Documents/soundworks-streaming-master/node_modules/soundworks/server/core/Service.js:19:24)
    at Sync.ready (/Users/computoruser/Documents/soundworks-streaming-master/node_modules/soundworks/server/services/Sync.js:43:10)

**Comment by b-ma** [comment]
Hi, 

The project is marked as deprecated for now, as we are heavily refactoring the streaming service.
You could however be able to make the project running by importing the develop branch of soundworks.

In package.json replace
```
"soundworks": "^2.1.9",
```
with
```
"soundworks": "github:collective-soundworks/soundworks#develop",
```
and reinstall the dependencies (note that you will need to remove the `package-lock.json` file as it doesn't work well with github dependencies).

Benjamin
